---
# This playbook contains common handlers that can be called in tasks.
 
# sudo service mysql restart (whether running or not)
- name: Restart gunicorn 
  service:
    name: gunicorn 
    state: restarted
    enabled: yes
