---
###INSTALL ANY PYTHON VERSION

- name: Install required package s
  apt: name={{item}} state=present
  with_items:
    - git 
    - python3-pip 
    - systemd 
    - postgresql-server-dev-all 
    - postgresql-client 
    - postgresql  
    - python-psycopg2
#    - wget 
#    - python-virtualenv 


- shell: "python3 --version"
  register: python_installed
- name: print a registered variable
  debug: var=python_installed.stderr_lines

- name: Install django, postgresql packages
  ansible.builtin.pip:
    name: "{{item}}" 
    executable: pip3
  with_items:
    - django==2.0
    - django-compressor
    - psycopg2==2.6.1 
    - djangorestframework==3.1.3 
    - django-filter==0.10.0  
    - markdown==2.6.2


- name: Create a vagrant user acting as the user vagrant (sudo su - postgres) 
  become_user: postgres 
  shell: "createuser vagrant -s"
  failed_when: false

- name: Create a new database wth specific encoding 
  become_user: postgres
  community.postgresql.postgresql_db:
    name: scrum 
    encoding: UTF-8

- name: Clone a repo with separate git directory
  ansible.builtin.git:
    repo: https://github.com/TorresAWS/djangorest 
    dest: /src/djangorest
    separate_git_dir: /src/djangorest.git

- name: Template a file to /etc/file.conf
  ansible.builtin.template:
    src: ./templates/test.service.j2
    dest: /etc/systemd/system/test.service 

- name: Make sure a service is running
  systemd:
    state: started
    name: test.service 



